
services:
  app:
    build:
      context: .
      target: java-stage
    ports:
      - 8080:8080

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example